### PR TITLE
return None and raise warning when transform_geom dst_ogr_geom is NULL

### PR DESCRIPTION
**Pull request by snowman2**
Related to: https://github.com/mapbox/rasterio/issues/1170

### CODE REVIEW

**Comment by snowman2** [comment]
All transformer tests pass. The failure is an unrelated test failure:
```
E           AttributeError: 'UnparsedPath' object has no attribute 'scheme'
```

**Comment by sgillies** [comment]
@snowman2 can you rebase this on the maint-1.9 branch ?

**Comment by sgillies** [comment]
@snowman2 oddly, this new test fails for me with GDAL 3.0.2. There's no warning and no failure to transform.

**Comment by snowman2** [comment]
Huh, that's interesting. I wonder what changed 🤔

**Pull request closed without merging**
