### PR TITLE
setup.py:  gdal_output out of scope

### PR DESCRIPTION
**Pull request by micahcochran**
Moving lines so the global variable gdal_output is in scope for copy_gdalapi function.  (Found when trying to build on Windows in OSGeo4W.)

### CODE REVIEW

**Comment by rbuffat** [comment]
this slipped by when I was refactoring. 
copy_gdalapi should not depend on gdal_output. Instead
format(gdal_output[3])) should be changed to format(gdalversion)

**Comment by micahcochran** [comment]
@rbuffat  That sounds like a better design.  I'll close this PR when you submit that one.

**Comment by micahcochran** [comment]
With this most recent push `python setup.py egg_info` is in this way:
```
Obtaining file:///home/travis/build/Toblerity/Fiona
    Traceback (most recent call last):
      File "<string>", line 20, in <module
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module
    
    ----------------------------------------
[31m    Command "python setup.py egg_info" failed with error code 1 in /home/travis/build/Toblerity/Fiona[0m
```

I'm not quite understanding the problem.

A quick internet search said upgrading pip by "pip install --upgrade setuptools".  I will update travis yaml to do that.

**Comment by micahcochran** [comment]
I've changed the code based on rbuffat's comment.

**Comment by sgillies** [comment]
@micahcochran will you please squash these 5 commits into 1?

**Comment by rbuffat** [comment]
@micahcochran sorry that I missed the comment about creating a PR on my own.

@sgillies Would it be useful to have a windows based CI?  When looking at gdal 2.0 and the new 64bit integer types it would be interesting to test some combinations of 32bit/64bit python 2.7 on windows. I started to play around with appveyor https://ci.appveyor.com/project/rbuffat/fiona but I did not manage yet to get a complete build with gdal from osgeo4w.

**Comment by micahcochran** [comment]
@sgillies I will squash them if someone can point me in the right direction.

@rbuffat Not a problem.  I've got some instructions on [getting Fiona to work on OSGeo4w](https://github.com/micahcochran/Geospatial-Python-Packages-for-OSGeo4W#fiona) that might help.  Let me know if they need work.

**Comment by geowurster** [comment]
@micahcochran The first two responses on this [StackOverflow](http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) thread explain the feature pretty well.

If you wanted to squash everything into your initial commit, you would do: `$ git rebase -i 7859c4b6434d9e57cc24d842d2e0a3c1056e3196`

**Comment by sgillies** [comment]
@micahcochran the reason why I'm asking for the commits to be squashed is that in 7 commits, there are only two net changes I see:

untitled

**Comment by micahcochran** [comment]
@sgillies I very much understand the issue.  I'm learning git, and at this very moment I don't have time to learn how to do this.

**Pull request closed without merging**
