### PR TITLE
WIP: Added Python 3.7 to Appveyor

### PR DESCRIPTION
**Pull request by snorfalorpagus**
This PR adds a build using Python 3.7 to Appveyor. I've also cleaned the config up a bit.

### CODE REVIEW

**Comment by sgillies** [comment]
@snorfalorpagus I'm not sure what to make of that first error. Should I re-run it?

**Comment by snorfalorpagus** [comment]
@sgillies It looks like a corrupt download of the gisinternals binaries. If you could re-run it my guess is it'll work.

My aim with this is to get Python 3.6 + 3.7 wheels for Windows that could be uploaded to PyPI.

**Comment by sgillies** [comment]
I re-built and it failed to extract the zip file again.

**Comment by snorfalorpagus** [comment]
I see what has gone wrong. That combination of MSVC/GDAL does not exist. I'll fix it now.

**Comment by snorfalorpagus** [comment]
One solution to the 2.7 issue is to use:

```
python -W ignore -m pip install ...
```

However it's used in several places and makes everything ugly for the sake of supporting Python 2.7 for a few more months.

This can also be done with an environment variable, but we'd want to unset it before running the tests as we still want to know about warnings in Fiona.

**Comment by snorfalorpagus** [comment]
Another temporary solution is to pin `pip` at an earlier version, before the deprecation warning was introduced.

**Comment by snorfalorpagus** [comment]
The issue seems to be that Appveyor is detecting the warning as an error because it's printed to stderr. Not sure how to fix this yet.

**Comment by snorfalorpagus** [comment]
I think this is ready for another look @sgillies.

I've switched the pip commands to use `cmd` instead of `ps` which prevents the deprecation error from causing the build to fail.

**Pull request merged**
