### PR TITLE
Travis-ci: added support for ppc64le along with amd64

### PR DESCRIPTION
**Pull request by sanjaymsh**
Hi,
I have added support for ppc64le build on travis-ci in the branch . The travis-ci build log can be tracked on the link :https://travis-ci.com/github/sanjaymsh/Fiona/builds/188878827 . I believe it is ready for the final review and merge.
Please have a look on it and if everything looks fine for you then please approve it for merge.

Thanks !!

### CODE REVIEW

**Comment by sgillies** [comment]
Hi @sanjaymsh can you give us some motivation for this PR? Do you have concerns that the standard linux builds do not address? Keep in mind that the fiona package is a fairly thin wrapper around GDAL. If the GDAL project isn't being tested, this may not be worth the effort.

**Comment by sanjaymsh** [comment]
Hi @sgillies This package is included in the distros for ppc64le - we are trying to make sure that integration into the distros is pain free by making sure they have a clean bill of health from their development community. This simplifies the integration process for ppc64le based distros.

**Comment by sgillies** [comment]
@sanjaymsh what would you think about trimming this to a single ppc64le job to keep the build time down? I don't think 3 jobs will catch any more architecture-specific problems than 1 job.

**Comment by sanjaymsh** [comment]
@sgillies Ok, yes, this way the time taken will be down. This approach looks good to me as well. In case if it is required to test on other matrix for ppc64 then it can be changed. For now, we can use the one which uses python:3.8. I will make changes accordingly.

Thanks!!

**Comment by sanjaymsh** [comment]
@sgillies I have updated the .travis.yml and removed ppc64le from matrix for all env , just kept one to make sure that it supports the ppc64le arch as well. And now it looks like all the issues are resolved and it is ready for the final review and merge. Please have a look on this.

Thanks !!

**Comment by sgillies** [comment]
Closing since we're leaving Travis CI.

**Pull request closed without merging**
