### PR TITLE
DEP: Pin cython>=3

### PR DESCRIPTION
**Pull request by snowman2**
Related: https://github.com/rasterio/rasterio/pull/2875

### CODE REVIEW

**Comment by mwtoews** [comment]
Thanks, the long-awaited Cython 3.0 has been released (e.g. [_InfoWorld_](https://www.infoworld.com/article/3702888/cython-30-the-next-generation-of-python-at-the-speed-of-c.html)).

The CI tests are still using Cython~=0.29.29 (from -r requirements-dev.txt (line 4)).

Are there any relevant items in the [migration guide](https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html) that should be considered?

**Comment by snowman2** [comment]
> The CI tests are still using Cython~=0.29.29 (from -r requirements-dev.txt (line 4)).

Thanks - updated.

**Comment by snowman2** [comment]
> Are there any relevant items in the [migration guide](https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html) that should be considered?

Possibly, but nothing pops out to me at the moment.

**Comment by mwtoews** [comment]
With a local build, the only thing that pops up for me is:
> warning: [fiona/_env.pyx:152](https://github.com/Toblerity/Fiona/blob/75d2ab16bb951357c7bd7788242e19bf1bf71b67/fiona/_env.pyx#L152):0: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310

this can be addressed later.

**Review by mwtoews — APPROVED** [review]

**Comment by snowman2** [comment]
See #1137

**Review by sgillies — APPROVED** [review]

**Pull request merged**
