### PR TITLE
Switch to pytest

### LINKED ISSUE #374: Switch to pytest for unittests
I have missed `@pytest.mark.parametrize()` for the last few PR's I submitted in addition to some other features.  Any objections?  I think just switching to `$ py.test` is little to no work, and we can migrate individual tests as needed moving forward.

### PR DESCRIPTION
**Pull request by geowurster**
Closes #374 

Also removes the ability to run unittests with `$ python setup.py test` but we don't mention that in the docs anyway.

### CODE REVIEW

**Comment by geowurster** [comment]
Not quite done chasing down all the edge cases that are failing in Travis.

**Comment by geowurster** [comment]
Looks like there's a GDAL 1.9 regression?  Appveyor is probably failing because I updated the install command in `.travis.yml` but not `.appveyor.yml`.

**Comment by sgillies** [comment]
Yeah, that's strange, @geowurster. We're still using GDAL 1.9.2 here, same as ever, right?

**Comment by geowurster** [comment]
@sgillies Yeah the Travis matrix is using `GDALVERSION=1.9.2` but I'll add a `$ gdal-config --version` to the setup script to make sure that's actually what we're going.

**Comment by micahcochran** [comment]
@geowurster   You could also also add 
```
$ fio --gdal-version
```

This was added this in PR #366.  I made that PR in preparation for testing  multiple GDAL version tests for Appveyor.

**Comment by geowurster** [comment]
The most recent build confirms we are using GDAL `1.9.2`:

```console
$ fio --gdal-version
+[[ -n '' ]]
+eval 'fio --gdal-version'
++fio --gdal-version
GDAL, version 1.9.2
```

```console
$ gdal-config --version
+[[ -n '' ]]
+eval 'gdal-config --version'
++gdal-config --version
1.9.2
```

**Comment by snorfalorpagus** [comment]
The failure reported by Travis is:

```
=================================== FAILURES ===================================

____________________ TarArchiveReadingTest.test_filter_vsi _____________________

self = <tests.test_vfs.TarArchiveReadingTest testMethod=test_filter_vsi>

    def test_filter_vsi(self):

        results = list(self.c.filter(bbox=(-114.0, 35.0, -104, 45.0)))

>       self.assertEqual(len(results), 67)

E       AssertionError: 66 != 67

tests/test_vfs.py:23: AssertionError
```

However, this test is currently skipped with nose: https://github.com/Toblerity/Fiona/blob/master/.travis.yml#L50
```
--exclude test_filter_vsi --exclude test_geopackage --exclude test_write_mismatch
```

**Comment by geowurster** [comment]
@snorfalorpagus Ah good point!  Will revisit tonight.

**Comment by geowurster** [comment]
Any ideas as to why Appveyor keeps failing?  Could someone with a working Windows dev environment test locally?

**Comment by snorfalorpagus** [comment]
The exception on Appveyor is:
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python34-x64\Lib\site-packages\_pytest\config.py", line 338, in _importconftest
    mod = conftestpath.pyimport()
  File "C:\Python34-x64\Lib\site-packages\py\_path\local.py", line 650, in pyimport
    __import__(modname)
  File "C:\Python34-x64\Lib\site-packages\_pytest\assertion\rewrite.py", line 207, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "C:\projects\fiona\tests\conftest.py", line 12, in <module>
    import fiona
  File "C:\projects\fiona\fiona\__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "C:\projects\fiona\fiona\collection.py", line 8, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: No module named 'fiona.ogrext'
```
It looks like `import fiona` is importing the version in `C:\projects`, not `site-packages`. Try calling `develop` instead of `install` in `setup.py`.

**Comment by geowurster** [comment]
@snorfalorpagus Thanks for retrieving the traceback.  I forgot to grab it.

I'll try switching to `develop`, but the install command remains unchanged so I would expect other PR's to be failing too.

**Comment by geowurster** [comment]
@snorfalorpagus You were right, `$ python setup.py develop` worked, although I don't quite understand why PR's before this one weren't failing.  Would you mind running these tests locally?  I don't have access to a Windows dev environment.

@sgillies This is ready for final 👀 .

**Pull request merged**
