### PR TITLE
Build wheel artifact on Appveyor

### PR DESCRIPTION
**Pull request by snorfalorpagus**
Trying to build a wheels for Windows using the gisinternals libraries on Appveyor. Submitting this PR to trigger the Appveyor builds.

### CODE REVIEW

**Comment by snorfalorpagus** [comment]
This looks like it's working now. When a build on Appveyor is successful it will store the wheel as an artifact. For example:

https://ci.appveyor.com/project/sgillies/fiona/build/job/kutvmbq94qo06ilg/artifacts

The wheels include all the necessary binaries for GDAL, GEOS etc in the `fiona/.libs` folder. I'm not sure if we need to include any licence files with these binaries also? What do we do for the linux/macOS wheels?

The build is configured it such a way that the wheel is tested, so if the tests pass it should be good to go.

When it comes to a release it should be a case of downloading the artifacts for the tagged commit and uploading them to pypi.

**Comment by sgillies** [comment]
@snorfalorpagus how exciting! I can confirm that there's an artifact for one of the builds:

untitled

The other builds are failing:

untitled

And here is the reason why with GDAL 1.11:

```
================================== FAILURES ===================================
________________________________ test_options _________________________________
tmpdir = local('C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pytest-of-appveyor\\pytest-0\\test_options0')
    def test_options(tmpdir):
        """Test that setting CPL_DEBUG=ON works"""
        logfile = str(tmpdir.mkdir('tests').join('test_options.log'))
        logger = logging.getLogger()
        logger.setLevel(logging.DEBUG)
        fh = logging.FileHandler(logfile)
        fh.setLevel(logging.DEBUG)
        logger.addHandler(fh)
    
        with fiona.drivers(CPL_DEBUG=True):
            path = os.path.join("tests", "data", "coutwildrnp.shp")
            c = fiona.open(path)
            c.close()
            with open(logfile, "r") as f:
                log = f.read()
>           assert "GDALClose" in log
E           assert 'GDALClose' in "Creating a not-responsible GDALEnv in drivers()\nGDAL_DATA: C:\\gdal\\bin\\gdal-data\nPROJ data files not located, PR...en(tests\\\\data\\\\coutwildrnp.shp/000000A8B16CE3A0) succeeded as ESRI Shapefile.'\nFlushed buffer\nStopped session\n"
tests\test_drivers.py:30: AssertionError
---------------------------- Captured stderr call -----------------------------
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
DEBUG:fiona._drivers:GDAL_DATA: C:\gdal\bin\gdal-data
WARNING:fiona._drivers:PROJ data files not located, PROJ_LIB not set
DEBUG:botocore.session:Loading variable profile from defaults.
DEBUG:botocore.session:Loading variable config_file from defaults.
DEBUG:botocore.session:Loading variable credentials_file from defaults.
DEBUG:botocore.session:Loading variable data_path from defaults.
DEBUG:botocore.session:Loading variable profile from defaults.
DEBUG:botocore.session:Loading variable region from defaults.
DEBUG:botocore.session:Loading variable profile from defaults.
DEBUG:botocore.session:Loading variable credentials_file from defaults.
DEBUG:botocore.session:Loading variable config_file from defaults.
DEBUG:botocore.session:Loading variable profile from defaults.
DEBUG:botocore.session:Loading variable metadata_service_timeout from defaults.
DEBUG:botocore.session:Loading variable profile from defaults.
DEBUG:botocore.session:Loading variable metadata_service_num_attempts from defaults.
DEBUG:botocore.session:Loading variable profile from defaults.
DEBUG:botocore.credentials:Looking for credentials via: env
DEBUG:botocore.credentials:Looking for credentials via: assume-role
DEBUG:botocore.credentials:Looking for credentials via: shared-credentials-file
DEBUG:botocore.credentials:Looking for credentials via: custom-process
DEBUG:botocore.credentials:Looking for credentials via: config-file
DEBUG:botocore.credentials:Looking for credentials via: ec2-credentials-file
DEBUG:botocore.credentials:Looking for credentials via: boto-config
DEBUG:botocore.credentials:Looking for credentials via: container-role
DEBUG:botocore.credentials:Looking for credentials via: iam-role
INFO:botocore.vendored.requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 169.254.169.254
DEBUG:botocore.utils:Caught exception while trying to retrieve credentials: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x000000A8B199A780>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
Traceback (most recent call last):
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\util\connection.py", line 88, in create_connection
    raise err
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\util\connection.py", line 78, in create_connection
    sock.connect(sa)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python36-x64\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python36-x64\Lib\site-packages\botocore\awsrequest.py", line 130, in _send_request
    self, method, url, body, headers, *args, **kwargs)
  File "C:\Python36-x64\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python36-x64\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python36-x64\Lib\site-packages\botocore\awsrequest.py", line 157, in _send_output
    self.send(msg)
  File "C:\Python36-x64\Lib\site-packages\botocore\awsrequest.py", line 242, in send
    return HTTPConnection.send(self, str)
  File "C:\Python36-x64\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\connection.py", line 155, in connect
    conn = self._new_conn()
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\connection.py", line 139, in _new_conn
    (self.host, self.timeout))
botocore.vendored.requests.packages.urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x000000A8B199A780>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\util\retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
botocore.vendored.requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x000000A8B199A780>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python36-x64\Lib\site-packages\botocore\utils.py", line 180, in _get_request
    response = requests.get(url, timeout=timeout)
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
botocore.vendored.requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x000000A8B199A780>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
DEBUG:botocore.utils:Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
DEBUG:fiona._drivers:GDAL_DATA: C:\gdal\bin\gdal-data
WARNING:fiona._drivers:PROJ data files not located, PROJ_LIB not set
DEBUG:fiona._drivers:CPLE_None in b'OGR: OGROpen(tests\\data\\coutwildrnp.shp/000000A8B16CE3A0) succeeded as ESRI Shapefile.'
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
------------------------------ Captured log call ------------------------------
__init__.py                348 DEBUG    Creating a not-responsible GDALEnv in drivers()
test_drivers.py             24 DEBUG    GDAL_DATA: C:\gdal\bin\gdal-data
test_drivers.py             24 WARNING  PROJ data files not located, PROJ_LIB not set
session.py                 287 DEBUG    Loading variable profile from defaults.
session.py                 287 DEBUG    Loading variable config_file from defaults.
session.py                 287 DEBUG    Loading variable credentials_file from defaults.
session.py                 287 DEBUG    Loading variable data_path from defaults.
session.py                 287 DEBUG    Loading variable profile from defaults.
session.py                 287 DEBUG    Loading variable region from defaults.
session.py                 287 DEBUG    Loading variable profile from defaults.
session.py                 287 DEBUG    Loading variable credentials_file from defaults.
session.py                 287 DEBUG    Loading variable config_file from defaults.
session.py                 287 DEBUG    Loading variable profile from defaults.
session.py                 287 DEBUG    Loading variable metadata_service_timeout from defaults.
session.py                 287 DEBUG    Loading variable profile from defaults.
session.py                 287 DEBUG    Loading variable metadata_service_num_attempts from defaults.
session.py                 287 DEBUG    Loading variable profile from defaults.
credentials.py            1661 DEBUG    Looking for credentials via: env
credentials.py            1661 DEBUG    Looking for credentials via: assume-role
credentials.py            1661 DEBUG    Looking for credentials via: shared-credentials-file
credentials.py            1661 DEBUG    Looking for credentials via: custom-process
credentials.py            1661 DEBUG    Looking for credentials via: config-file
credentials.py            1661 DEBUG    Looking for credentials via: ec2-credentials-file
credentials.py            1661 DEBUG    Looking for credentials via: boto-config
credentials.py            1661 DEBUG    Looking for credentials via: container-role
credentials.py            1661 DEBUG    Looking for credentials via: iam-role
connectionpool.py          203 INFO     Starting new HTTP connection (1): 169.254.169.254
utils.py                   183 DEBUG    Caught exception while trying to retrieve credentials: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x000000A8B199A780>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
Traceback (most recent call last):
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\util\connection.py", line 88, in create_connection
    raise err
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\util\connection.py", line 78, in create_connection
    sock.connect(sa)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python36-x64\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python36-x64\Lib\site-packages\botocore\awsrequest.py", line 130, in _send_request
    self, method, url, body, headers, *args, **kwargs)
  File "C:\Python36-x64\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python36-x64\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python36-x64\Lib\site-packages\botocore\awsrequest.py", line 157, in _send_output
    self.send(msg)
  File "C:\Python36-x64\Lib\site-packages\botocore\awsrequest.py", line 242, in send
    return HTTPConnection.send(self, str)
  File "C:\Python36-x64\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\connection.py", line 155, in connect
    conn = self._new_conn()
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\connection.py", line 139, in _new_conn
    (self.host, self.timeout))
botocore.vendored.requests.packages.urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x000000A8B199A780>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\packages\urllib3\util\retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
botocore.vendored.requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x000000A8B199A780>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Python36-x64\Lib\site-packages\botocore\utils.py", line 180, in _get_request
    response = requests.get(url, timeout=timeout)
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python36-x64\Lib\site-packages\botocore\vendored\requests\adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
botocore.vendored.requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x000000A8B199A780>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
utils.py                   218 DEBUG    Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
collection.py              149 DEBUG    GDAL_DATA: C:\gdal\bin\gdal-data
collection.py              149 WARNING  PROJ data files not located, PROJ_LIB not set
collection.py              158 DEBUG    CPLE_None in b'OGR: OGROpen(tests\\data\\coutwildrnp.shp/000000A8B16CE3A0) succeeded as ESRI Shapefile.'
collection.py              412 DEBUG    Flushed buffer
collection.py              414 DEBUG    Stopped session
----------- coverage: platform win32, python 3.6.4-final-0 -----------
Name                                                      Stmts   Miss  Cover   Missing
---------------------------------------------------------------------------------------
C:\Python36-x64\Lib\site-packages\fiona\__init__.py         106      4    96%   204, 305, 345-346
C:\Python36-x64\Lib\site-packages\fiona\collection.py       295     28    91%   64, 78, 129, 131, 133, 142, 146, 163-164, 184, 186, 244-247, 253, 268, 270, 281, 296, 298, 309, 325-330, 340, 374
C:\Python36-x64\Lib\site-packages\fiona\compat.py            13      4    69%   7-8, 14-15
C:\Python36-x64\Lib\site-packages\fiona\crs.py               26      0   100%
C:\Python36-x64\Lib\site-packages\fiona\drvsupport.py        28      7    75%   163, 166-171
C:\Python36-x64\Lib\site-packages\fiona\errors.py            11      0   100%
C:\Python36-x64\Lib\site-packages\fiona\fio\__init__.py       0      0   100%
C:\Python36-x64\Lib\site-packages\fiona\fio\bounds.py        55      1    98%   83
C:\Python36-x64\Lib\site-packages\fiona\fio\calc.py          28      1    96%   58
C:\Python36-x64\Lib\site-packages\fiona\fio\cat.py           53      9    83%   53, 55, 78-83, 85, 88-90
C:\Python36-x64\Lib\site-packages\fiona\fio\collect.py      135     31    77%   45, 47, 124, 136, 138, 140-160, 168, 170, 173-188, 194, 213-215
C:\Python36-x64\Lib\site-packages\fiona\fio\distrib.py       27      4    85%   37, 39-41
C:\Python36-x64\Lib\site-packages\fiona\fio\dump.py         104     58    44%   50, 52, 57, 76-162, 171-173, 181-183
C:\Python36-x64\Lib\site-packages\fiona\fio\env.py           15      9    40%   21-29
C:\Python36-x64\Lib\site-packages\fiona\fio\filter.py        24      1    96%   51
C:\Python36-x64\Lib\site-packages\fiona\fio\helpers.py       45      6    87%   39-42, 61, 112-113
C:\Python36-x64\Lib\site-packages\fiona\fio\info.py          41      3    93%   71-73
C:\Python36-x64\Lib\site-packages\fiona\fio\insp.py          26     17    35%   20-46
C:\Python36-x64\Lib\site-packages\fiona\fio\load.py          63      0   100%
C:\Python36-x64\Lib\site-packages\fiona\fio\ls.py            12      0   100%
C:\Python36-x64\Lib\site-packages\fiona\fio\main.py          23      0   100%
C:\Python36-x64\Lib\site-packages\fiona\fio\options.py       20      0   100%
C:\Python36-x64\Lib\site-packages\fiona\fio\rm.py            19      4    79%   19, 23-25
C:\Python36-x64\Lib\site-packages\fiona\inspector.py         17     17     0%   2-40
C:\Python36-x64\Lib\site-packages\fiona\io.py                31      3    90%   51, 62, 102
C:\Python36-x64\Lib\site-packages\fiona\rfc3339.py           39      0   100%
C:\Python36-x64\Lib\site-packages\fiona\transform.py          5      1    80%   41
C:\Python36-x64\Lib\site-packages\fiona\vfs.py               42      0   100%
---------------------------------------------------------------------------------------
TOTAL                                                      1303    208    84%
 1 failed, 661 passed, 2 skipped, 1 deselected, 1 xfailed, 5 xpassed in 666.88 seconds 
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
```

"GDALClose" won't show up in the log with GDAL 1.11 right?

**Comment by sgillies** [comment]
@snorfalorpagus I'm going to have to get moving on giving you access to this AppVeyor account or create a new one we can collaborate on.

**Comment by snorfalorpagus** [comment]
> "GDALClose" won't show up in the log with GDAL 1.11 right?

I think this issue is unrelated. See #569.

**Comment by snorfalorpagus** [comment]
This is good to go.

**Pull request merged**
