### PR TITLE
Add support for Google Cloud Storage

### PR DESCRIPTION
**Pull request by theduckylittle**
Adds the appropriate prefix to support Google Cloud Storage.

Requires support in GDAL (2.3 or newer).

### CODE REVIEW

**Comment by sgillies** [comment]
@theduckylittle as with https://github.com/mapbox/rasterio/pull/1577 this needs more work, the good news is that you can copy from Rasterio (or the other way around).

**Comment by theduckylittle** [comment]
Added session support and here's a nifty example of it in use:
```
(fiona-env) ducky@thinkduck ~/Projects/mapserver/Fiona $ fio info gs://bnd-uploads/bbox2.geojson
{"schema": {"geometry": "Polygon", "properties": {"name": "str"}}, "count": 1, "driver": "GeoJSON", "crs": "EPSG:4326", "name": "bbox2", "bounds": [-131.484375, 21.94304553343818, -63.28125, 50.064191736659104], "crs_wkt": "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]"}
```

**Comment by sgillies** [comment]
@theduckylittle would you be willing to aim this PR at the maint-1.8 branch instead of master? Then I would include it in 1.8.5.

**Comment by theduckylittle** [comment]
Closing this one in favor of #709  based against the maintenance branch.

**Pull request closed without merging**
