### PR TITLE
Python38/Windows dll load directory for maint-1.8

### PR DESCRIPTION
**Pull request by rbuffat**
I created a clean PR for maint-1.8 based on https://github.com/Toblerity/Fiona/pull/852

### CODE REVIEW

**Comment by rbuffat** [comment]
Coveralls is not configured on appveyor and the changes only affect windows.

**Comment by sgillies** [comment]
@rbuffat thank you very much!

**Comment by rbuffat** [comment]
Thanks for reviewing the PR! @sgillies @snorfalorpagus @s7726

**Comment by sgillies** [comment]
Resolves #851

**Pull request merged**
