### PR TITLE
Polyline m support

### PR DESCRIPTION
**Pull request by marouaneloutfi**
Following the issue #[774](https://github.com/Toblerity/Fiona/issues/774), this PR establishes support for Measurement values in shapefiles for both single point and LineString geometries.
it would also be the first step in many towards extending M-values support  to modules using Fiona for read/write purposes such as Geopandas.

### CODE REVIEW

**Comment by sgillies** [comment]
@marouaneloutfi are you a subscriber at https://fiona.groups.io/g/dev? I'd like to have a discussion there about this PR as it will be a fairly big change.

**Comment by marouaneloutfi** [comment]
@sgillies I've just subscribed to the dev group, I am looking forward to hearing your thoughts on this.

**Comment by sgillies** [comment]
@marouaneloutfi I'm back from vacation and would like to get this moving again. I may not have been clear before, but I'm looking to you to take the lead on explaining the need for M support in Fiona, the design, interoperability considerations and things like that. I bet that with a good introductory email, other developers will indicate interest and/or have suggestions.

**Comment by sgillies** [comment]
This is too old now. We should start fresh after 1.9.0 comes out.

**Pull request closed without merging**
