### PR TITLE
Drop unittest from collection tests

### PR DESCRIPTION
**Pull request by QuLogic**
With #654, this means there's no more unittest.

### CODE REVIEW

**Comment by sgillies** [comment]
🥇 @QuLogic

**Comment by sgillies** [comment]
@QuLogic no blame from me, but this change is tripping up the wheel builds for macOS and Python 2.7: https://travis-ci.com/sgillies/fiona-wheels/jobs/154518129. I've very recently switched from developing on a MacBook to developing on a Linux laptop and that's why the issue wasn't caught before the tagged commit went to the wheel builder.

I've restarted the build job to check whether it was a transient error and it has failed again. Since all the other jobs have passed, I'm asking myself whether there is a tarfile bug specific to OS X on this version of Python 2.7.

I may have to revert the changes to TestTarArchiveReading until after we ship 1.8.0.

**Comment by QuLogic** [comment]
That link is to a job that passed?

**Comment by sgillies** [comment]
Oops, I forgot that I re-ran it after force pushing to the tag (questionable, I know) and now the history is lost.

**Comment by QuLogic** [comment]
Can you try the build again so I can see what the error was?

**Comment by sgillies** [comment]
@QuLogic check here in ~15 minutes: https://travis-ci.com/sgillies/fiona-wheels/builds/89538021.

**Comment by QuLogic** [comment]
OK, well, I don't quite understand the failure there. I don't have a mac either, so I can't really debug much. If you add macOS CI, then I can try and re-do it.

**Pull request merged**
