### PR TITLE
Initial impl of MemoryFile for Fiona

### PR DESCRIPTION
**Pull request by sgillies**
Towards resolution of #500.

Reading bytes from a `MemoryFile` is not yet working.

### CODE REVIEW

**Comment by sgillies** [comment]
In Rasterio, `MemoryFile` uses numpy to get the size of the buffer written to the memory file by rasterio. We want to avoid, for now, requiring numpy for Fiona and will need a different way.

**Comment by snorfalorpagus** [comment]
Looks like you forgot to add `fiona.io` (and maybe `fiona._io`?) to the commit.

**Comment by sgillies** [comment]
Woo hoo, it's working 🎉

**Comment by snorfalorpagus** [comment]
This looks good to me. I think it would be useful to add some examples in the tests for using this with a `BytesIO` and a Python file object (from regular `open()`).

**Pull request merged**
