### PR TITLE
travis bump gdal to 3.0

### PR DESCRIPTION
**Pull request by rbuffat**
Gdal 3.0.0 was released. This PR switches gdal 2.5.0beta1 with gdal 3.0.0.

### CODE REVIEW

**Comment by sgillies** [comment]
@rbuffat can you allow builds with 3.0.0 to fail? We don't support it yet.

**Comment by sgillies** [comment]
We've got odd failures on Appveyor: we're testing with `-m "not wheel"` but still some tests marked "wheel" like https://ci.appveyor.com/project/sgillies/fiona/builds/24426912/job/ajlsorcf2i9xldml#L1248 are being run, and they fail. I'm inclined to merge this anyway. Okay, @snorfalorpagus ?

**Comment by rbuffat** [comment]
@sgillies  @snorfalorpagus  Do we miss [here](https://github.com/Toblerity/Fiona/blob/master/appveyor.yml#L141) a ` -m "not wheel"`?

**Comment by sgillies** [comment]
@rbuffat yes, that must be the problem.

**Comment by rbuffat** [comment]
@sgillies  sorry for hijacking this PR. I added "not wheel" to appveyor and removed the gdal 1x tests.

**Pull request merged**
