### PR TITLE
Add Appveyor for Windows CI.

### PR DESCRIPTION
**Pull request by micahcochran**
In Windows, skip some erroring and failing tests by reporting FIXME on Windows.  A few DeprecationWarnings were fixed in unit tests.  Minor modifications to a few test.

@rbuffat gave me a good starting point.

Refer to issue #313 for more details.

This tests Python 3.4.3 using GDAL 1.11.4 using Windows 64-bit.

This skips ~~34~~ 38 tests that are either failing or raising errors.  One tests `/dev/null`, which is not applicable for Windows and should always be skipped.

This PR should be a starting point to do Windows testing on more configurations of Python/GDAL/Win32&64.  It should also highlight that there is some unit test work for Windows support.

[Appveyor Test Results](https://ci.appveyor.com/project/micahcochran/fiona/build/1.0.46)

An [Appveyor](http://www.appveyor.com/) account will need to be enabled to make testing happend automatically.

Note: setUpClass/tearDownClass is a Python 2.7+ unittest feature which the backport unittest2 could be made to fulfill.

### CODE REVIEW

**Comment by sgillies** [comment]
@micahcochran great! I'll look into an Appveyor account and review the skips.

**Comment by sgillies** [comment]
@micahcochran I've begun to configure Appveyor, can you resolve the conflicts in this PR and commit? We might get an Appveyor build!

**Comment by micahcochran** [comment]
@sgillies    PR #357 was causing the conflict.  I was able to get it to pass.  On Windows, 41 tests are being skipped.  If you want to merge it just squash and merge.

**Comment by sgillies** [comment]
@micahcochran thank you!

**Comment by micahcochran** [comment]
Thank you!

**Comment by geowurster** [comment]
@sgillies Any way to add project contributors to the Appveyor account?  The behavior mentioned in https://github.com/Toblerity/Fiona/pull/373#issuecomment-239900680 blocks the queue whenever a change is pushed until all of the builds time out.  Appveyor respects `[ci skip]` in commit messages, but it would be nice to have the option to cancel builds for situations like this where only letting a couple tests fail is enough to know the problem is persisting.

**Comment by sgillies** [comment]
@geowurster currently I'm using my personal appveyor account. I can add you as a contributor if you're signed up for Appveyor and give me the email that identifies your account. Longer term, it might be good to make a new account and team that we can share, but I don't have time for that until I get back from FOSS4G and settle into the school year.

**Comment by geowurster** [comment]
@sgillies 👍 We can track in https://github.com/Toblerity/Fiona/issues/380.

I created an Appveyor account through my GitHub account, but it is attached to `wursterk@gmail.com`.

**Pull request merged**
