### PR TITLE
Initial attempt at fiona.remove for deleting data sources

### PR DESCRIPTION
**Pull request by snorfalorpagus**
As suggested in #285.

This was slightly more tricky than I initially realised, as OGR needs to know which driver to use in order to delete the data source.

I've only implemented this for GDAL 1.x for now, and still need to write the function documentation. Posting here for comment.

### CODE REVIEW

**Comment by sgillies** [comment]
@snorfalorpagus looks like a good start. We'll need tests.

I'm going to do something about refactoring the .pyx files so we're not repeating ourselves. It might be possible to write `_remove()` just once for both versions of GDAL.

**Comment by snorfalorpagus** [comment]
@sgillies I actually wrote some tests, but forgot to stage the file.

When `driver` isn't specified by the user, should we make an attempt at guessing based on file extension, rather than just assuming `ESRI Shapefile`? We can't just scroll through all the possible drivers like we do for `open` as the operation is destructive.

**Comment by sgillies** [comment]
@snorfalorpagus no guessing, please. I could see that becoming a large amount of fragile code. We should make the driver argument required if the input isn't a collection.

**Comment by snorfalorpagus** [comment]
I think this is working now. If it looks OK, I'll squash the commits together.

**Comment by snorfalorpagus** [comment]
I forgot, this isn't quite finished as the call I'm using for delete is deprecated - need to explore when the new call became available.

**Comment by rbuffat** [comment]
@snorfalorpagus 
OGR_Dr_DeleteDataSource is deprecated for gdal2x. Thus in ogrext1.pyx (for gdal1x in the current implementation) OGR_Dr_DeleteDataSource is the one to use, in ogrext2.pyx (gdal2x) you can use GDALDeleteDataset.

Maybe a check for ODrCDeleteDataSource would be nice?

**Comment by snorfalorpagus** [comment]
@rbuffat Sounds good to me.

Note to self: `OGR_Dr_TestCapability`

**Comment by snorfalorpagus** [comment]
I've added a check for the driver capability, but not sure how to test it. I tested locally with the GMT driver, but that doesn't seem to be available on Travis (and may not be on other users machines).

Also switched to `GDALDeleteDataset` in GDAL 2.x.

**Pull request merged**
